@startuml admission_workflow_reactor
skinparam defaultTextAlignment center

start

repeat
  :Reactor changed;
  ->ADDED, MODIFIED event;
  if (ServiceAccount exists?) then (yes)
    if (status.phase\n==\nAccepted) then (yes)
      :Store in Cache;
      :Reconciliation;
      stop
    endif
  else (no)
    if (status.phase\n==\nRejected) then (yes)
      if (status.failureReasons\n==\nnew failureReasons) then (yes)
        :do nothing;
        stop
      endif
    endif
  endif
  :update status\nand\ndo nothing;


@enduml
