@startuml ../../static/img/docs/workflows/reactor-admission
skinparam defaultTextAlignment center

start

repeat
  #yellow:Reactor added or modified]
  if (spec.serviceAccountName exists?) then (no)
  elseif (status.phase == Accepted) then (no)
  else (yes)
    #palegreen:Store in Cache>
    #palegreen:Reconcile pipelines>
    stop
  endif
  #pink:update status.failureReasons|
  if (status.phase == Rejected) then (no)
  elseif (status.failureReasons changed) then (yes)
  else (no)
    stop
  endif
  #pink:update status.phase|
@enduml