@startuml container_operator
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(ops, "OPS", "In charge of cluster management and maintainance")
Person(cibot, "CI Bot", "Automatic deployment process")

System_Boundary(sys_kubirds, "Kubirds") {
  Container(c_kubirds_operator, "Operator", "Schedule monitoring tasks according to the current monitoring configuration")
  Container(c_kubirds_dashboard, "Dashboard", "Visualize current cluster state")
}

System_Ext(sys_tekton, "TektonCD", "Task Scheduling System")
System_Ext(sys_k8s, "Kubernetes", "Cluster Workload Management System")

Rel_R(sys_tekton, sys_k8s, "schedule workload", "HTTPS")
Rel_D(c_kubirds_operator, sys_tekton, "run monitoring task", "HTTPS")
Rel_D(c_kubirds_operator, sys_k8s, "watch monitoring configuration", "HTTPS")

Rel_L(cibot, sys_k8s, "setup the monitoring configuration", "HTTPS")
Rel_D(ops, sys_k8s, "setup the monitoring configuration", "kubectl")
Rel_D(ops, c_kubirds_dashboard, "visit the dashboard", "kubectl proxy")
Rel_L(c_kubirds_dashboard, c_kubirds_operator, "query GraphQL API", "HTTPS")

@enduml
